apiVersion: v1
kind: Service
metadata:
  name: my-java-app
  namespace: ocp-pipelines-examples
  labels:
    app: my-java-app
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: my-java-app