apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-samples
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/astanez/hetzner-epyc-ocp-gitops.git' # Replace with your repo URL
    targetRevision: HEAD
    path: tekton-samples
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ocp-tekton-examples
  syncPolicy:
    automated:
      prune: true
      selfHeal: true