
apiVersion: v1
kind: Namespace
metadata:
  name: 04-dev-gitops-prj
  labels:
    # This label allows Argo CD to manage resources inside this namespace
    argocd.argoproj.io/instance: openshift-gitops 
    # This enables OpenShift's cluster monitoring for your apps
    openshift.io/cluster-monitoring: "true"
  annotations:
    # Good for documentation in a shared KVM lab
    openshift.io/description: "Development environment for Python Flask App"
    openshift.io/display-name: "Dev Project"

